/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Binary, InstantiateMsg, ExecuteMsg, QueryMsg, ArrayOfCountsResponse, CountsResponse, ArrayOfKeyValueResponse, KeyValueResponse, ArrayOfBinary, Addr, GuardiansListResp, Uint64, ArrayOfVotesResponse, VotesResponse, OAuthGuardian, ArrayOfOAuthGuardian, ArrayOfOAuthVotesResponse, OAuthConfig, OAuthAttestationProof } from "./SocialRecovery.types";
export interface SocialRecoveryReadOnlyInterface {
  contractAddress: string;
  pubkey: () => Promise<Binary>;
  guardiansList: () => Promise<GuardiansListResp>;
  threshold: () => Promise<Uint64>;
  votes: () => Promise<ArrayOfVotesResponse>;
  counts: () => Promise<ArrayOfCountsResponse>;
  getData: ({
    key
  }: {
    key: string;
  }) => Promise<KeyValueResponse>;
  getAllData: () => Promise<ArrayOfKeyValueResponse>;
  getSecret: () => Promise<Binary>;
  getShare: ({
    address
  }: {
    address: string;
  }) => Promise<Binary>;
  getAllShares: () => Promise<ArrayOfBinary>;
  getRecoverData: ({
    address
  }: {
    address: string;
  }) => Promise<Binary>;
  getAllRecoverData: () => Promise<ArrayOfBinary>;
  oAuthGuardiansList: () => Promise<ArrayOfOAuthGuardian>;
  oAuthVotes: () => Promise<ArrayOfOAuthVotesResponse>;
  oAuthConfigQuery: () => Promise<OAuthConfig>;
  getOAuthShare: ({ subHash }: { subHash: string }) => Promise<Binary>;
}
export class SocialRecoveryQueryClient implements SocialRecoveryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.pubkey = this.pubkey.bind(this);
    this.guardiansList = this.guardiansList.bind(this);
    this.threshold = this.threshold.bind(this);
    this.votes = this.votes.bind(this);
    this.counts = this.counts.bind(this);
    this.getData = this.getData.bind(this);
    this.getAllData = this.getAllData.bind(this);
    this.getSecret = this.getSecret.bind(this);
    this.getShare = this.getShare.bind(this);
    this.getAllShares = this.getAllShares.bind(this);
    this.getRecoverData = this.getRecoverData.bind(this);
    this.getAllRecoverData = this.getAllRecoverData.bind(this);
    this.oAuthGuardiansList = this.oAuthGuardiansList.bind(this);
    this.oAuthVotes = this.oAuthVotes.bind(this);
    this.oAuthConfigQuery = this.oAuthConfigQuery.bind(this);
    this.getOAuthShare = this.getOAuthShare.bind(this);
  }
  pubkey = async (): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pubkey: {}
    });
  };
  guardiansList = async (): Promise<GuardiansListResp> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guardians_list: {}
    });
  };
  threshold = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      threshold: {}
    });
  };
  votes = async (): Promise<ArrayOfVotesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      votes: {}
    });
  };
  counts = async (): Promise<ArrayOfCountsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      counts: {}
    });
  };
  getData = async ({
    key
  }: {
    key: string;
  }): Promise<KeyValueResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_data: {
        key
      }
    });
  };
  getAllData = async (): Promise<ArrayOfKeyValueResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_all_data: {}
    });
  };
  getSecret = async (): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_secret: {}
    });
  };
  getShare = async ({
    address
  }: {
    address: string;
  }): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_share: {
        address
      }
    });
  };
  getAllShares = async (): Promise<ArrayOfBinary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_all_shares: {}
    });
  };
  getRecoverData = async ({
    address
  }: {
    address: string;
  }): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_recover_data: {
        address
      }
    });
  };
  getAllRecoverData = async (): Promise<ArrayOfBinary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_all_recover_data: {}
    });
  };
  oAuthGuardiansList = async (): Promise<ArrayOfOAuthGuardian> => {
    return this.client.queryContractSmart(this.contractAddress, {
      o_auth_guardians_list: {}
    });
  };
  oAuthVotes = async (): Promise<ArrayOfOAuthVotesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      o_auth_votes: {}
    });
  };
  oAuthConfigQuery = async (): Promise<OAuthConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      o_auth_config_query: {}
    });
  };
  getOAuthShare = async ({ subHash }: { subHash: string }): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_o_auth_share: {
        sub_hash: subHash
      }
    });
  };
}
export interface SocialRecoveryInterface extends SocialRecoveryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updatePubkey: ({
    newPubkey
  }: {
    newPubkey: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  recover: ({
    newPubkey
  }: {
    newPubkey: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  revoke: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  storeData: ({
    key,
    value
  }: {
    key: string;
    value: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  removeData: ({
    key
  }: {
    key: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  storeSecret: ({
    value
  }: {
    value: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  removeSecret: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  storeShare: ({
    value
  }: {
    value: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  removeShare: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  storeRecoverData: ({
    value
  }: {
    value: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  removeRecoverData: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  recoverWithOAuth: ({ attestation, newPubkey }: { attestation: OAuthAttestationProof; newPubkey: Binary }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  revokeOAuth: ({ attestation }: { attestation: OAuthAttestationProof }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  storeOAuthShare: ({ attestation, value }: { attestation: OAuthAttestationProof; value: Binary }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class SocialRecoveryClient extends SocialRecoveryQueryClient implements SocialRecoveryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updatePubkey = this.updatePubkey.bind(this);
    this.recover = this.recover.bind(this);
    this.revoke = this.revoke.bind(this);
    this.storeData = this.storeData.bind(this);
    this.removeData = this.removeData.bind(this);
    this.storeSecret = this.storeSecret.bind(this);
    this.removeSecret = this.removeSecret.bind(this);
    this.storeShare = this.storeShare.bind(this);
    this.removeShare = this.removeShare.bind(this);
    this.storeRecoverData = this.storeRecoverData.bind(this);
    this.removeRecoverData = this.removeRecoverData.bind(this);
    this.recoverWithOAuth = this.recoverWithOAuth.bind(this);
    this.revokeOAuth = this.revokeOAuth.bind(this);
    this.storeOAuthShare = this.storeOAuthShare.bind(this);
  }
  updatePubkey = async ({
    newPubkey
  }: {
    newPubkey: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_pubkey: {
        new_pubkey: newPubkey
      }
    }, fee_, memo_, funds_);
  };
  recover = async ({
    newPubkey
  }: {
    newPubkey: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      recover: {
        new_pubkey: newPubkey
      }
    }, fee_, memo_, funds_);
  };
  revoke = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      revoke: {}
    }, fee_, memo_, funds_);
  };
  storeData = async ({
    key,
    value
  }: {
    key: string;
    value: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      store_data: {
        key,
        value
      }
    }, fee_, memo_, funds_);
  };
  removeData = async ({
    key
  }: {
    key: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_data: {
        key
      }
    }, fee_, memo_, funds_);
  };
  storeSecret = async ({
    value
  }: {
    value: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      store_secret: {
        value
      }
    }, fee_, memo_, funds_);
  };
  removeSecret = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_secret: {}
    }, fee_, memo_, funds_);
  };
  storeShare = async ({
    value
  }: {
    value: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      store_share: {
        value
      }
    }, fee_, memo_, funds_);
  };
  removeShare = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_share: {}
    }, fee_, memo_, funds_);
  };
  storeRecoverData = async ({
    value
  }: {
    value: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      store_recover_data: {
        value
      }
    }, fee_, memo_, funds_);
  };
  removeRecoverData = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_recover_data: {}
    }, fee_, memo_, funds_);
  };
  recoverWithOAuth = async ({ attestation, newPubkey }: { attestation: OAuthAttestationProof; newPubkey: Binary }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      recover_with_o_auth: {
        attestation,
        new_pubkey: newPubkey
      }
    }, fee_, memo_, funds_);
  };
  revokeOAuth = async ({ attestation }: { attestation: OAuthAttestationProof }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      revoke_o_auth: {
        attestation
      }
    }, fee_, memo_, funds_);
  };
  storeOAuthShare = async ({ attestation, value }: { attestation: OAuthAttestationProof; value: Binary }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      store_o_auth_share: {
        attestation,
        value
      }
    }, fee_, memo_, funds_);
  };
}
