import Head from 'next/head';
import {
  Box,
  Divider,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
  Input,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { FaHome } from "react-icons/fa";
import {
  WalletSection,
  StakingSection,
} from '../components';
import { defaultCA, defaultChainName } from '../config';
import { useBalances } from '../hooks/useBalances';
import { useChain } from '@cosmos-kit/react';
import { SigningStargateClient } from '@cosmjs/stargate';
import { useEffect, useState } from 'react';
import { useAA } from '../hooks/useAA';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  const {  } = useChain(defaultChainName);

  const [recipient, setRecipient] = useState<string | undefined>(undefined); 
  const [amount, setAmount] = useState<string | undefined>(undefined);
  const [newkey, setNewkey] = useState<string | undefined>(undefined);  

  const {balance, txHash, handleSend} = useBalances(amount, recipient);

  const {pubkey, userPubkey, threshold, guardians, counts, votes, txHash: txHashA, handleRecover } = useAA(newkey);

  const handleAmount = (event: any) => {
    setAmount(event.target.value);
  }

  const handleRecipient = (event: any) => {
    setRecipient(event.target.value);
  }

  const handleNewkey = (event: any) => {
    setNewkey(event.target.value);
  }

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Client</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === 'light' ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
        <Button variant="outline" px={0} ml={2} onClick={() => window.location.href = "/"}>
          <Icon
            as={FaHome}
          />
        </Button>
      </Flex>
      {/* <Box textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: '3xl', sm: '4xl', md: '5xl' }}
          fontWeight="extrabold"
          mb={3}
        >
        </Heading>
      </Box> */}
      <WalletSection isMultiChain={false} />
      <p>
        Balance: {balance} stake 
      </p>
      <Input placeholder='Address' value={recipient} onChange={handleRecipient} />
      <Input placeholder='Amount' value={amount} onChange={handleAmount} />
      <Button onClick={() => handleSend()}>Send tokens!</Button>
      <p>txHash: {txHash}</p>
      <p>pubkey: {userPubkey}</p>
      <Divider />
      <Input placeholder='New Pubkey' value={newkey} onChange={handleNewkey} />
      <Button onClick={() => handleRecover()}>Recover!</Button>
      <p>txHash: {txHashA}</p>
      {/* <StakingSection chainName={defaultChainName} /> */}
      <Box mb={3}>
        <Divider />
      </Box>
      <p>
        SmartContract: {defaultCA} 
      </p>
      <p>
        Owner pubkey: { pubkey } 
      </p>
      <p>
        Threshold: { threshold } 
      </p>
      <p>
        Guardians: { guardians?.guardians.join(" | ") } 
      </p>
      <p>
        Counts: { counts?.map((count) => `\n ${count.pubkey}: ${count.votes}/${threshold} votes`) } 
      </p>
      <p>
        Votes: { votes?.map((vote) => `\n ${vote.addr} votes for: ${vote.vote}`) } 
      </p>
      <Box mb={3}>
        <Divider />
      </Box>
      <Stack
        isInline={true}
        spacing={1}
        justifyContent="center"
        opacity={0.5}
        fontSize="sm"
      >
        <Text>Built with</Text>
        <Link
          href="https://cosmology.tech/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cosmology
        </Link>
      </Stack>
    </Container>
  );
}