/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  guardians: string[];
  oauth_config?: OAuthConfig | null;
  oauth_guardians?: OAuthGuardian[] | null;
  pubkey: Binary;
  threshold: number;
}
export type ExecuteMsg = {
  update_pubkey: {
    new_pubkey: Binary;
  };
} | {
  recover: {
    new_pubkey: Binary;
  };
} | {
  revoke: {};
} | {
  store_data: {
    key: string;
    value: Binary;
  };
} | {
  remove_data: {
    key: string;
  };
} | {
  store_secret: {
    value: Binary;
  };
} | {
  remove_secret: {};
} | {
  store_share: {
    value: Binary;
  };
} | {
  remove_share: {};
} | {
  store_recover_data: {
    value: Binary;
  };
} | {
  remove_recover_data: {};
} | {
  recover_with_o_auth: {
    attestation: OAuthAttestationProof;
    new_pubkey: Binary;
  };
} | {
  revoke_o_auth: {
    attestation: OAuthAttestationProof;
  };
} | {
  store_o_auth_share: {
    attestation: OAuthAttestationProof;
    value: Binary;
  };
};
export interface OAuthGuardian {
  provider: string;
  sub_hash: string;
}
export interface OAuthConfig {
  attestor_pubkey?: Binary | null;
  google_issuer: string;
  expected_audience: string;
  max_clock_skew: number;
}
export type OAuthAttestationAction = "recover" | "revoke" | "store_share";
export interface OAuthAttestation {
  action: OAuthAttestationAction;
  chain_id: string;
  contract: string;
  expires_at: number;
  new_pubkey?: Binary | null;
  nonce: string;
  provider: string;
  share_hash?: string | null;
  sub_hash: string;
}
export interface OAuthAttestationProof {
  attestation: OAuthAttestation;
  signature: Binary;
}
export interface OAuthVotesResponse {
  sub_hash: string;
  vote: string;
}
export type ArrayOfOAuthVotesResponse = OAuthVotesResponse[];
export type ArrayOfOAuthGuardian = OAuthGuardian[];
export type QueryMsg = {
  pubkey: {};
} | {
  guardians_list: {};
} | {
  threshold: {};
} | {
  votes: {};
} | {
  counts: {};
} | {
  get_data: {
    key: string;
  };
} | {
  get_all_data: {};
} | {
  get_secret: {};
} | {
  get_share: {
    address: string;
  };
} | {
  get_all_shares: {};
} | {
  get_recover_data: {
    address: string;
  };
} | {
  get_all_recover_data: {};
} | {
  o_auth_guardians_list: {};
} | {
  o_auth_votes: {};
} | {
  o_auth_config_query: {};
} | {
  get_o_auth_share: {
    sub_hash: string;
  };
};
export type ArrayOfCountsResponse = CountsResponse[];
export interface CountsResponse {
  pubkey: string;
  votes: number;
}
export type ArrayOfKeyValueResponse = KeyValueResponse[];
export interface KeyValueResponse {
  key: string;
  value: Binary;
}
export type ArrayOfBinary = Binary[];
export type Addr = string;
export interface GuardiansListResp {
  guardians: Addr[];
}
export type Uint64 = number;
export type ArrayOfVotesResponse = VotesResponse[];
export interface VotesResponse {
  addr: Addr;
  vote: string;
}
